name: Release PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
        with:
          skip-install-on-cache-hit: 'true'
      - run: pnpm install
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run version
          title: "Upcoming Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
