name: "Lint Packages"

on:
  workflow_call:
    secrets:
      CAP_GH_RELEASE_TOKEN:
        required: true

jobs:
  lint:
    runs-on: "macos-15"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token }}

      - name: "Setup Tools"
        uses: ./.github/actions/setup-tools

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: "Lint Packages"
        shell: bash
        run: |
          pnpm nx affected --target=lint
