name: "Setup"

on:
  workflow_call:
    secrets:
      CAP_GH_RELEASE_TOKEN:
        required: true

jobs:
  setup:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token }}

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Setup Tools"
        uses: ./.github/actions/setup-tools
        with:
          skip-install-on-cache-hit: "true"
