name: Unit Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  unittest-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Run ios-engine unit tests
        run: cd ./packages/ios-engine && swift package clean && swift test
  
