name: Unit Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  unittest-ios:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run:  xcrun simctl list devices
      - name: Run ios-engine unit tests
        run: cd ./packages/ios-engine && swift test
  
